title: Colour guesser
hero_image: images/banner.png
description: Make a game where you 
theme: yellow # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Getting started
- title: Setting text
- title: Setting colours 
- title: Random colours
- title: Looping over a list
- title: Picking and checking the answer
- title: Resetting the game
- title: Challenge — Background colour to winning colour then back to white on reset